### ISSUE TITLE
ideal menu

### ISSUE THREAD

**Issue by ATN35** [WildCodeSchool-2024-02/JS-Nantes-RamCSS-P3-WattMap#109]
![Capture d’écran 2024-07-25 103037](https://github.com/user-attachments/assets/9d8e8c2f-823f-4431-81b5-7f63a6ab720d)

**Comment by Acetoshi** [comment]
Please be more precise.

**Comment by MartinFest** [comment]
Je propose ça 
![image](https://github.com/user-attachments/assets/7a681394-7a00-4229-bfdb-bfe8d56d86bf)

**Comment by Acetoshi** [comment]
Fixed

**Comment by MartinFest** [comment]
done by David
